package ca.ubc.ctlt.encryption;

import blackboard.data.user.User;
import blackboard.persist.Id;
import org.apache.commons.codec.binary.Hex;


/**
 * A wrapper class of BB user class with encryption feature.
 */
public class UserWrapper extends User {
    /** Autogenerated serial id */
	private static final long serialVersionUID = 3305762688278240853L;
	private User user;
    private Encryption encryptor;
    private boolean isEncrypt;
    private boolean isRandomEmailName = false;
    private String pseudoDomain;

    public UserWrapper(User user, Encryption encryptor, boolean isEncrypt) {
        this.user = user;
        this.encryptor = encryptor;
        this.isEncrypt = isEncrypt;
        // use user ID external string as initialization vector
        this.encryptor.setIv(user.getId().getExternalString());
    }

    public void setRandomEmailName(boolean isRandomEmailName) {
        this.isRandomEmailName = isRandomEmailName;
    }

    public void setPseudoDomain(String pseudoDomain) {
        this.pseudoDomain = pseudoDomain;
    }

    /**
     * Internal ID is used to retrieve other information. So no encryption
     * @return  Id
     */
    public Id getId() {
        return user.getId();
    }

    public String getExternalId() {
        return isEncrypt ? encryptor.encrypt(user.getId().getExternalString(), Encryption.DEFAULT_IV) : user.getId().getExternalString();
    }

    public String getUsername() {
        return isEncrypt ? encryptor.encrypt(user.getUserName(), Encryption.DEFAULT_IV) : user.getUserName();
    }

    public String getStudentId() {
        return isEncrypt ? encryptor.encrypt(user.getStudentId(), Encryption.DEFAULT_IV) : user.getStudentId();
    }

    public String getBatchUid() {
        return isEncrypt ? encryptor.encrypt(user.getBatchUid(), Encryption.DEFAULT_IV) : user.getBatchUid();
    }

    public String getEmailAddress() {
        if (!isEncrypt) {
            return user.getEmailAddress();
        }

        String value = user.getEmailAddress();
        if (value == null) {
            return null;
        }
        String[] email = value.split("@");

        if (isRandomEmailName) {
            // generate a random string for email name. Using 25 characters to avoid collision with the really ones.
            // Gmail allow 30 max.
            email[0] = new String(Hex.encodeHex(Encryption.hashKey(email[0]))).substring(0, 25);
        } else {
            // or encrypt the email name
            email[0] = encryptor.encrypt(email[0]);
        }

        String domain = email.length > 1 ? email[1] : "";
        domain = (null == pseudoDomain || pseudoDomain.isEmpty()) ? domain : pseudoDomain;
        System.out.print(email[0] + "@" + domain);
        return email[0] + "@" + domain;
    }

    public String getGivenName() {
        return isEncrypt ? encryptor.encrypt(user.getGivenName()) : user.getGivenName();
    }

    public String getFamilyName() {
        return isEncrypt ? encryptor.encrypt(user.getFamilyName()) : user.getFamilyName();
    }

    public String getFullName() {
        String fullname = user.getGivenName();
        if ((user.getMiddleName() != null) && (user.getMiddleName().length() > 0)) {
            fullname += " " + user.getMiddleName();
        }
        fullname += " " + user.getFamilyName();

        return isEncrypt ? encryptor.encrypt(fullname) : fullname;
    }

    public SystemRole getSystemRole() {
        return user.getSystemRole();
    }

    public String getLocale() {
        return user.getLocale();
    }
}
